import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import HeaderMenu from "../components/HeaderMenu/HeaderMenu"
import HeaderReal from "../components/HeaderReal/HeaderReal"

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        <HeaderReal />
        <HeaderMenu />
        {children}
        </body>
        </html>
    )
}
