"use client"

import './globals.css'
import {Inter} from 'next/font/google'
import Toggle from "@/components/Toggle/Toggle";

const inter = Inter({subsets: ['latin']})

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html>
        <head>
            <script src="../gojs/release/go.js"></script>
        </head>
        <body>
        <Toggle />
        </body>
        </html>
    )
}
